server:
  port: 9102
  
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: LPOSpringAuthenticationDB   
  application:
    name: SPRING-AUTHENTICATION

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost